enquete/agenda_de_tarefas/urls.py
from django.urls import path
from . import views

app_name ='agenda_de_tarefas'

urlpatterns = [
    path('', views.entrar, name='root'),

    path('sair/', views.sair, name='sair'),

    path('tarefas/', views.tarefas, name='tarefas'),

    path('detalhe_tarefa/<int:tarefa_id>/', views.detalhe_tarefa, name='detalhe_tarefa'),

    path('busca/', views.busca, name='busca'),

]

enquete/enquete/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

enquete/main/urls.py
from django.urls import path
from . import views

app_name ='main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('enquete/<int:pk>', views.DetalhesView.as_view(), name='detalhes'),

    path('enquete/<int:pk>/resultado', views.ResultadoView.as_view(), name='resultado'),

    path('', views.ListarComentariosView.as_view(), name='listar_comentario'),

    path('enquete/<int:pk>/comentario', views.DetalhesComentariosView.as_view(), name='detalhes_comentario'),

    path('enquete/<int:id_enquete>/votacao', views.votacao, name='votacao'),
]

enquete/agenda_de_tarefas/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING
from django.utils import timezone
from django.contrib.auth.models import User


class TipoDeTarefa(models.Model):
    tipo_de_tarefa = models.CharField(
        default='T',
        max_length=1000,
        choices=(
            ("Trabalho", "Trabalho"),
            ("Casa", "Casa"),
            ("Pessoal", "Pessoal"),
            ("Outros", "Outros"),
        ),
        blank=False, null=False
    )

    def __str__(self):
        return self.tipo_de_tarefa

class Usuario(models.Model):
    usuario = models.OneToOneField(User, on_delete=DO_NOTHING, verbose_name="usuario")

    def __str__(self):
        return self.usuario

class Tarefa(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(max_length=100)
    dia = models.DateTimeField(default=timezone.now)
    mostrar = models.BooleanField(default=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    tipotarefa = models.OneToOneField(TipoDeTarefa, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime

class Pergunta(models.Model):
    texto = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('Data de Publicação')
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora - datetime.timedelta(days=1) <= self.data_publicacao <= agora
    publicada_recentemente.admin_order_field = 'data_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'ultimas 24hs?'

class Opcao(models.Model):
    texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

class Comentario(models.Model):
    autor_comentario = models.CharField(max_length=150)
    texto = models.CharField(max_length=200)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    data_publicacao = models.DateTimeField('Data de Publicação')
    def __str__(self):
        return self.autor_comentario
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora - datetime.timedelta(days=1) <= self.data_publicacao <= agora

enquete/agenda_de_tarefas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import auth, messages
from django.core.paginator import Paginator
from django.db.models import Q
from agenda_de_tarefas import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

@login_required(redirect_field_name='root')
def tarefas(request):
    tarefas = models.Tarefa.objects.all().filter(
        mostrar = True
    )
    paginator = Paginator(tarefas, 3)

    page = request.GET.get('p')
    tarefas = paginator.get_page(page)

    return render(request, 'agenda_de_tarefas/tarefas.html', {'tarefas':tarefas,})

#================================================
@login_required(redirect_field_name='root')
def detalhe_tarefa(request, tarefa_id):
    detalhetarefa = get_object_or_404(models.Tarefa, id = tarefa_id)

    if not detalhetarefa.mostrar:
        raise Http404()
    #return HttpResponseRedirect(reverse('agenda_de_tarefas:detalhe_tarefa'))
    return render(request, 'agenda_de_tarefas/detalhes_tarefa.html', {'detalhetarefa':detalhetarefa,})

#================================================
@login_required(redirect_field_name='root')
def busca(request):
    termo = request.GET.get('termo')

    tarefas = models.Tarefa.objects.order_by('-id').filter( Q(nome__icontains = termo), mostrar = True)
    paginator = Paginator(tarefas, 4)

    page = request.GET.get('p')
    tarefas = paginator.get_page(page)

    return render(request, 'agenda_de_tarefas/buscar_tarefas.html', {'tarefas':tarefas})

#================================================

def entrar(request):
    if request.method != "POST":
        return render(request, 'agenda_de_tarefas/index.html')

    nome = request.POST.get('usuario')
    senha = request.POST.get('senha')
    user = authenticate( username = nome, password = senha)

    if user == None:
        return render(request, 'agenda_de_tarefas/index.html')
    else:
        auth.login(request, user = user)
        return HttpResponseRedirect(reverse('agenda_de_tarefas:tarefas'))

#================================================

def sair(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('agenda_de_tarefas:root'))

enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from main import models

class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'ultimas_perguntas'
    def get_queryset(self):
        return models.Pergunta.objects.filter(
            data_publicacao__lte = timezone.now()
            ).order_by('-data_publicacao')[:5]

class DetalhesView(generic.DetailView):
    model = models.Pergunta
    template_name = 'main/detalhes.html'
    def get_queryset(self):
        return models.Pergunta.objects.filter(data_publicacao__lte = timezone.now())

class ListarComentariosView(generic.ListView):
    template_name = 'main/detalhes.html'
    context_object_name = 'ultimos_autores'
    def get_queryset(self):
        return models.Comentario.objects.filter(
            data_publicacao__lte = timezone.now()
            ).order_by('-data_publicacao')[:5]

class DetalhesComentariosView(generic.DetailView):
    model = models.Comentario
    template_name = 'main/detalhes_comentario.html'
    def get_queryset(self):
        return models.Comentario.objects.filter(data_publicacao__lte = timezone.now())

class ResultadoView(generic.DetailView):
    model = models.Pergunta
    template_name = 'main/resultado.html'

def votacao(request, id_enquete):
    pergunta = get_object_or_404(models.Pergunta, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except(KeyError, models.Opcao.DoesNotExist):
        return render(request, 'main/detalhes.html', {
            'pergunta':pergunta,
            'error_message':"Selecione uma opção válida!"
        })
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
    return HttpResponseRedirect(
        reverse('main:resultado', args=(pergunta.id,))
    )

#def index(request):
#    ultimas_perguntas = models.Pergunta.objects.order_by('-data_publicacao')[:5]
#    contexto = {'ultimas_perguntas':ultimas_perguntas}
#    return render(request, 'main/index.html', contexto)

#def detalhes(request, id_enquete):
#    pergunta = get_object_or_404(models.Pergunta, pk=id_enquete)
#    return render(request, 'main/detalhes.html', {'pergunta':pergunta})

#def resultado(request, id_enquete):
#    pergunta = get_object_or_404(models.Pergunta, pk=id_enquete)
#    return render(request, 'main/resultado.html', {'pergunta':pergunta})

enquete/agenda_de_tarefas/templates/agenda_de_tarefas/buscar_tarefas.html
{% extends 'base.html' %}

{% block conteudo %}
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'busca_tarefa' %}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Procurar tarefa</button>  
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="termo" value="{{ request.GET.termo }}" aria-label="Tarefa">
    </form>

    <h1>TIPOS DE TAREFAS</h1>
    
    {% for tarefa in tarefas %}
        
        {% if tarefa.usuario == user %}
            <a href="{% url 'detalhe_tarefa' tarefa.id %}">{{ tarefa.nome }}</a><br>
            {{tarefa.descricao}}<br>
            {{tarefa.dia}}<br>
            {{tarefa.usuario}}<br>
            {{tarefa.tipotarefa}}<br>
        {% endif %}
    {% endfor %}

{% endblock %}

enquete/agenda_de_tarefas/templates/agenda_de_tarefas/detalhes_tarefa.html
{% extends 'base.html' %}

{% block conteudo %}
<dl>
    
    <dt>Nome</dt>
    <dd>{{ detalhetarefa.nome }}</dd>

    <dt>descrição</dt>
    <dd>{{ detalhetarefa.descricao }}</dd>

    <dt>Data criação</dt>
    <dd>{{ detalhetarefa.dia }}</dd>

</dl>



{% endblock %}

enquete/agenda_de_tarefas/templates/agenda_de_tarefas/index.html
{% extends 'base.html' %}

{% block conteudo %}
<a href="http://victoraugusto1994.pythonanywhere.com/admin/auth/user/add/">Adicinando novos usuarios</a></br>
<a href="http://victoraugusto1994.pythonanywhere.com/admin/auth/user/">Altenticar usuarios</a>
    <form method="POST" action="{% url 'agenda_de_tarefas:root' %}">
        {% csrf_token %}
        <div class="form-group">
            <label>Usuário</label>
            <input type="text" name="usuario" value="{{ request.POST.usuario }}" class="form-control">
        </div>
        <div class="form-group">
            <label>Senha</label>
            <input type="password" name="senha" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Entrar</button>
    </form>

{% endblock %}

enquete/agenda_de_tarefas/templates/agenda_de_tarefas/tarefas.html
{% extends 'base.html' %}

{% block conteudo %}
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'agenda_de_tarefas:busca' %}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Procurar tarefa</button>
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="termo" value="{{ request.GET.termo }}" aria-label="Tarefa">
    </form>
        <a href="{% url 'agenda_de_tarefas:sair' %}">sair do sistema</a>
    <h1>TIPOS DE TAREFAS</h1>
        <a href="http://victoraugusto1994.pythonanywhere.com/admin/agenda_de_tarefas/tipodetarefa/">Adicinar tipos de ativdades</a></br>
        <a href="http://victoraugusto1994.pythonanywhere.com/admin/agenda_de_tarefas/tarefa/add/">Adicionar novas tarefas</a>
    <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Dia</th>
            <th>Tipo de Tarefa</th>
          </tr>
        </thead>
        <tbody>

            {% for tarefa in tarefas %}
                {% if tarefa.usuario == user %}
                    <tr>
                        <td>
                        <a href="{% url 'agenda_de_tarefas:detalhe_tarefa' tarefa.id %}">{{ tarefa.nome }}</a>
                        </td>
                        <td>{{tarefa.descricao}}</td>
                        <td>{{tarefa.dia}}</td>
                        <td>{{tarefa.tipotarefa}}</td>
                    </tr>
                {% endif %}
          {% endfor %}

        </tbody>
      </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% for pagina in tarefas.paginator.page_range %}
            {% if contatos.number == pagina %}
              <li class="page-item active">
                <a class="page-link" href="?p={{ pagina }} & termo={{ request.GET.termo }}">{{ pagina }}</a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?p={{ pagina }}& termo={{ request.GET.termo }}">{{ pagina }}</a>
              </li>
            {% endif %}
          {% endfor %}
        </ul>
    </nav>

{% endblock %}

enquete/agenda_de_tarefas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>{% block titulo %}{%endblock%}</title>
</head>
<body>
    {% include 'parciais/_nav.html' %}
    {% block conteudo %}
    
    
    
    
    {%endblock%}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

enquete/agenda_de_tarefas/templates/parciais/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'agenda_de_tarefas:tarefas' %}">Lista de Tarefas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"></ul>
  </div>
</nav>

enquete/main/templates/main/detalhes.html
<html>
    <head>
        <title>App Enquete</title>
    </head>
    <body>
        <h2>Detalhes da enquete {{ pergunta.id }}</h2>
        <u>Pergunta</u>: {{pergunta.texto}}<br>
        <u>Data de Publicação</u>: {{pergunta.data_publicacao}}

        {% if error_message %}
            <hr>
            <strong>{{ error_message }}</strong>
            <hr>
        {% endif %}

        <form action="{% url 'main:votacao' pergunta.id %}" method="post">
            {% csrf_token %}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li><input type="radio" id="opcao{{ forloop.counter }}" name="opcao" value="{{ opcao.id }}">
                        <label for="opcao{{ forloop.counter }}">
                            {{ opcao.texto }}
                        </label>
                    </li>
                {% endfor %}
            </ul>
            <input type="submit" value="Registre o seu Voto">
        </form>
        <hr>
           <ul>
                {% for autor_comentario in pergunta.comentario_set.all %}
                    <li><a href="{% url 'main:detalhes_comentario' autor_comentario.id %} ">
                        {{ autor_comentario.texto }}
                    </a></li>
                {% endfor %}
            </ul>
    </body>
</html>

enquete/main/templates/main/detalhes_comentario.html
<html>
    <head>
        <title>App Enquete</title>
    </head>
    <body>
        <u>Comentários autor</u>: {{comentario.autor_comentario}}<br>
        <u>Data de Publicação</u>: {{comentario.data_publicacao}}        
        <hr>
        
        {% for comentario in comentario_set.all %}
            {{ comentario.texto }}             
        {% endfor %}
          
        <hr>
        <a href="{% url 'main:detalhes' comentario.pergunta.id %}">Deseja votar novamente?</a> |
        <a href="{% url 'main:index' %}">Retornar à Página Principal</a>

    </body>
</html>

enquete/main/templates/main/index.html
{% load static %}
<html>
    <head>
    <title>App Enquete</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    </head>
    <body>

        {% if ultimas_perguntas %}
            <h2>Lista das Últimas Enquetes</h2>
            <ul>
                {% for pergunta in ultimas_perguntas %}
                    <li><a href="{% url 'main:detalhes' pergunta.id %} ">
                        {{ pergunta.texto }}
                    </a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Nenhuma questão disponivel!!!</p>
        {% endif %}

    </body>
</html>

enquete/main/templates/main/resultado.html
<html>
    <head>
        <title>App Enquete</title>
    </head>
    <body>

        <h2>Resultado Parcia da Enquete {{ pergunta.id }}</h2>
        <u>Pergunta</u>: {{pergunta.texto}}<br>
        <u>Data de Publicação</u>: {{pergunta.data_publicacao}}
        <ul>
            {% for opcao in pergunta.opcao_set.all %}
                <li>{{ opcao.texto }} = {{ opcao.votos }}
                voto{{ opcao.votos | pluralize }}</li>
            {% endfor %}
        </ul>
        <hr>
        <a href="{% url 'main:detalhes' pergunta.id %}">Deseja votar novamente?</a> |
        <a href="{% url 'main:index' %}">Retornar à Página Principal</a>
    </body>
</html>